; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Active Status"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "Ryan Piazza"
#define MyAppExeName "active-status.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DEE81FBC-EFA4-4A0A-8DDD-CFD971079127}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=active-status-setup
SetupIconFile=assets\w2k_info.ico
SolidCompression=yes
WizardStyle=modern polar

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

Filename: "schtasks"; \
    Parameters: "/Create /F /SC DAILY /TN ""Active Status"" /TR ""{app}\{#MyAppExeName}"""; \
    Flags: runhidden waituntilterminated

[Code]
var
  CredentialsPage: TInputFileWizardPage;

procedure InitializeWizard();
begin
  CredentialsPage := CreateInputFilePage(
    wpSelectDir,
    'Import Credentials',
    'Select your .env credentials file',
    'Credentials file (.env):'
  );
  CredentialsPage.Add(
    '',
    'Environment files|*.env|All files|*.*',
    '.env'
  );
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  SourceFile, DestFile: String;
begin
  if CurStep = ssPostInstall then
  begin
    SourceFile := CredentialsPage.Values[0];
    DestFile := ExpandConstant('{app}\.env');
    if SourceFile <> '' then
      FileCopy(SourceFile, DestFile, False);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  if CurUninstallStep = usPostUninstall then
  begin      
      Exec('schtasks', '/Delete /F /TN "Active Status"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
      DelTree(ExpandConstant('{app}'), True, True, True);
    end;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if CurPageID = CredentialsPage.ID then
  begin
    if CredentialsPage.Values[0] = '' then
    begin
      MsgBox('Please select a credentials file before continuing.', mbError, MB_OK);
      Result := False;
    end;
  end;
end;
